export {
    getWheatleyData, 
    getDunbarData, 
    getHammonData, 
    FETCH_WHEATLEY_POEM_DATA_START, 
    FETCH_WHEATLEY_POEM_DATA_SUCCESS, 
    FETCH_WHEATLEY_POEM_DATA_FAILURE,
    FETCH_DUNBAR_POEM_DATA_START, 
    FETCH_DUNBAR_POEM_DATA_SUCCESS,
    FETCH_DUNBAR_POEM_DATA_FAILURE,
    FETCH_HAMMON_POEM_DATA_START, 
    FETCH_HAMMON_POEM_DATA_SUCCESS, 
    FETCH_HAMMON_POEM_DATA_FAILURE, 
} from '../actions/poemActions.js'; 